api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns

from api import views

urlpatterns = [
    url(r'^users/$', views.UserProfileList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[\d]+)/$', views.UserProfileDetail.as_view(), name='user-detail'),
    url(r'^projects/$', views.ProjectView.as_view(), name='project-list'),
    url(r'^projects/(?P<pk>[\d]+)/$', views.ProjectDetail.as_view(), name='project-detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = [
    url(r'^$', views.homeView, name='home'),
    url(r'^login/$', views.loginView, name='login'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^create_project/$', views.create_project),
    url(r'^logout/$', views.logout_user, name='logout'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projex/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'projex.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include('api.urls', namespace='api')),
    url(r'^', include('home.urls', namespace='home')),
   	url(r'^dash/', include('manager.urls', namespace='manager')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(max_length=55, widget=forms.TextInput(
									attrs={
										'placeholder': 'Username or Email',
										'class': 'text-input m-b-5'
									}
								))
	password = forms.CharField(max_length=55, widget=forms.PasswordInput(
									attrs={
										'placeholder': 'Password',
										'class': 'text-input m-b-2'
									}
								))

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

from home.forms import LoginForm
from manager.models import UserProfile

def homeView(request):
	context = {}

	# if user is logged in, redirect to dashboard
	if request.user.is_authenticated():
		context['logged_in'] = True

	return render(request, 'home.html', context)

def loginView(request):
	# Initialize context dictionary
	context = {}
	# Include the Login Form
	form = LoginForm()

	# If the user is logged in already, redirect to their dashboard
	if request.user.is_authenticated():
		return redirect(reverse('manager:dashboard'))

	# Check if form was submitted
	if request.method == 'POST':
		form = LoginForm(request.POST)
		# If there are no errors in the form
		if form.is_valid():
			# Collect the data
			username = request.POST['username']
			password = request.POST['password']
			# Try to associate the username and password with a user
			try:
				user = authenticate(username=username, password=password)
				# If a user was returned, check that the user is active
				if user is not None:
					# If the user is active, log the user in
					if user.is_active:
						user_profile = UserProfile.objects.get(user=user)
						login(request, user)
						return redirect(reverse('manager:dashboard'))
					# Return an 'account disabled' message if user is inactive
					else:
						messages.add_message(request, messages.INFO, 'Account Disabled')
			# Return an 'invalid login' message	if no user found for data
			except User.DoesNotExist:
				context['user_dne'] = "Your username or password was incorrect."

	context['form'] = form
	resp = render(request, "login.html", context)
	return resp;

home/templates/base.html
<!DOCTYPE html>
	{% load static from staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.min.css" />
		<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'home/css/base.css' %}" />
		{% block stylesheets %}
		{% endblock %}
		<!--[if lt IE 9]>
		    <script src="{% static 'home/js/html5shiv-printshiv.min.js' %}"></script>
		<![endif]-->

		<title>{% block title %}Projex{% endblock %}</title>
		{% block metaog %}
	    	<meta name="description" content="Projex" />
	    {% endblock %}
	</head>
	<body>
		<header>
			<div class="row clearfix">
				<div class="col-nav col-centered no-pad clearfix">
					<a href="/" class="navbar-logo">projex</a>
					<a href="#" class="pull-right" id="collapsed">&#x2261;</a>
					<nav class="navbar-collapsable right-menu pull-right">
						<ul class="menu-links">
							<li><a href="#">Features</a></li>
							<li><a href="#">Pricing</a></li>
							<li><a href="#">Sign Up</a></li>
							{% if not logged_in %}
								<li><a href="{% url 'home:login' %}">Log In</a></li>
							{% else %}
								<li><a href="{% url 'manager:dashboard' %}">Dashboard</a></li>
							{% endif %}
						</ul>
					</nav>
				</div>
			</div>
		</header>
			<div class="dashboard-row clearfix" id="first-thing">
				{% block content %}
				{% endblock %}
			</div>
		</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

		{% block javascript %}
		{% endblock %}

	</body>
</html>

home/templates/home.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'home/css/style.css' %}" />
	{% endblock %}


	{% block content %}
		<div class="container">
			<div class="overlay">
				<div class="col-3-4 col-centered" id="main">
					<h1 id="brief" class="p-t-20">Project management, but better.</h1>
					<h3 id="desc">Programmable software with real-time features to make collaborating as a team and meeting deadlines easier than ever before.</h3>
				</div>
			</div>
		</div>
	{% endblock %}

	{% block javascript %}
		<script src="{% static 'home/js/home.js' %}"></script>
	{% endblock %}

home/templates/login.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}

	{% endblock %}


	{% block content %}
		<div class="container">
				<div id="s-login" class="col-login col-centered white-box p-t-2 p-b-5 p-l-5 p-r-5">
					{% if not logged_in %}
						<h1 class="text-center p-b-5">Log In</h1>
						{% if user_dne %}
							<p class="error m-b-5">{{ user_dne }}</p>
						{% endif %}
						<form method="post" action="{% url 'home:login' %}">
							{% csrf_token %}
							<!--{% for f in form %}
								<span class="login-label">{{ f.label }}:</span><br />
								{{ f }}<br />
							{% endfor %}-->
							{{ form.as_table }}
							<input type="submit" class="submit" value="Log In">
						</form>
					{% else %}
						<h1 class="text-center p-t-2">You are logged in</h1>
					{% endif %}
				</div>
			</div>
	{% endblock %}

	{% block javascript %}

	{% endblock %}