api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns

from api import views

urlpatterns = [
    url(r'^users/$', views.UserProfileList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[\d]+)/$', views.UserProfileDetail.as_view(), name='user-detail'),
    url(r'^projects/$', views.ProjectView.as_view(), name='project-list'),
    url(r'^projects/(?P<pk>[\d]+)/$', views.ProjectDetail.as_view(), name='project-detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^create_project/$', views.create_project),
    url(r'^logout/$', views.logout_user, name='logout'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projex/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'projex.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include('api.urls', namespace='api')),
    url(r'^', include('home.urls', namespace='home')),
   	url(r'^dash/', include('manager.urls', namespace='manager')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

manager/models.py
from django.db import models
from django.contrib.auth.models import User

from manager.utils import get_image_path


class UserProfile(models.Model):
	user = models.OneToOneField(User)
	job_title = models.CharField(max_length=150, null=True)
	company = models.CharField(max_length=150, null=True)
	is_manager = models.BooleanField(default=False)

	def __unicode__(self):
		return self.user.username

class Project(models.Model):
	created_by = models.ForeignKey(UserProfile, null=True)
	name = models.CharField(max_length=150, null=True)
	description = models.CharField(max_length=255, null=True)
	date_created = models.DateTimeField(auto_now_add=True)
	icon = models.FileField(upload_to=get_image_path, blank=True, null=True)

	def __unicode__(self):
		return self.name

manager/forms.py
from django import forms

class NewProjectForm(forms.Form):
	name = forms.CharField(max_length=155, widget=forms.TextInput(
										attrs={
											'placeholder': 'Assign a name to your project',
											'class': 'text-input m-b-5',
										}
									))
	description = forms.CharField(max_length=140, widget=forms.TextInput(
										attrs={
											'placeholder': 'Give some details about the project',
											'class': 'text-input m-b-5'
										}
									))
	icon = forms.FileField(required=False, widget=forms.FileInput(
										attrs={
											'class': 'm-b-2'
										}
									))

manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
import json

from manager.forms import NewProjectForm
from manager.models import Project, UserProfile

# Create your views here.
def dashboard(request):
	context = {}
	context['logged_in'] = True
	context['user'] = request.user.pk
	context['form'] = NewProjectForm
	return render(request, 'index.html', context)

def logout_user(request):
	logout(request)
	return redirect(reverse('home:home'))

def create_project(request):
	if request.method == 'POST':
		project_name = request.POST.get('project_name')
		project_description = request.POST.get('project_description')
		project_author = UserProfile.objects.get(user=request.user)

		project = Project.objects.create(created_by=project_author, name=project_name, description=project_description)
		project.save()

		response_data = {'result': 'success'}

		return HttpResponse(
			json.dumps(response_data),
			content_type = "application/json"
		)
	else:
		return HttpResponse(
			json.dumps({'result': 'failure'}),
			content_type = "application/json"
		)

manager/templates/dashboard-base.html
<!DOCTYPE html>
	{% load static from staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.min.css" />
		<link rel="stylesheet" href="{% static 'home/css/base.css' %}" />
		{% block stylesheets %}
		{% endblock %}
		<!--[if lt IE 9]>
		    <script src="{% static 'home/js/html5shiv-printshiv.min.js' %}"></script>
		<![endif]-->

		<title>{% block title %}Projex{% endblock %}</title>
		{% block metaog %}
	    	<meta name="description" content="Projex" />
	    {% endblock %}
	</head>
	<body>
		<header>
			<div class="row">
				<div class="col-nav col-centered no-pad clearfix">
					<a href="/" class="navbar-logo">projex</a>
					<a href="#" class="pull-right" id="collapsed">&#x2261;</a>
					<nav class="navbar-collapsable right-menu pull-right">
						<ul class="menu-links">
							<li><a href="#" class="active">Projects</a></li>
							<li><a href="#">My Tasks</a></li>
							<li><a href="#">Mentions</a></li>
							<li><a href="#">Messages</a></li>
							<li><a href="#">Settings</a></li>
							<li><a href="{% url 'manager:logout' %}">Logout</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
			<div class="dashboard-row clearfix">
				{% block content %}
				{% endblock %}
			</div>
		</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

		{% block javascript %}
		{% endblock %}

	</body>
</html>

manager/templates/index.html
{% extends 'dashboard-base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'manager/css/style.css' %}" />
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	{% endblock %}

	{% block content %}
		<div id="add-project-overlay">
			<p id="add-project-exit">&#x2715;</p>
			<div class="col-1-3 col-centered" id="add-project">
				<form action="#" method="POST" enctype="multipart/form-data" id="add_project">
					{% csrf_token %}
					{{ form.as_p }}
					<input type="submit" class="submit" value="Create Project">
				</form>
			</div>
		</div>
		<div class="col-1-5 actions">
			<a href="#add-proj" class="add-project"><i class="fa fa-plus"></i><span class="p-l-5">add project</span></a>
		</div>
		<div class="col-4-5 dash">
			
		</div>
	{% endblock %}

	{% block javascript %}
		<script type="text/javascript">
			var user = {{ user }};
		</script>
		<script src="{% static 'manager/js/js.js' %}"></script>
	{% endblock %}